movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('update/<int:pk>', views.update, name='update'),
    ]

pair/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class Review(models.Model):
  title = models.CharField(max_length=80)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

movies/views.py
from django.shortcuts import render, redirect
from .models import Review

# Create your views here.
def index(request):
    movies = Review.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

def new(request):

    return render(request, 'movies/new.html')

def create(request):
    title = request.GET.get('title_')
    content = request.GET.get('content_')
    Review.objects.create(title=title, content=content)

    return redirect('movies:index')

def detail(request, pk):
    movie_click = Review.objects.get(id=pk)

    context = {
        'title': movie_click.title, 
        'content': movie_click.content,
        'idx' : movie_click.pk,
    }
    return render(request, 'movies/detail.html', context)

def delete(request, pk):
    Review.objects.get(id=pk).delete()

    return redirect('movies:index')

def edit(request, pk):
    edit_review = Review.objects.get(id=pk)
    context = {
        'edit': edit_review,
    }
    return render(request, 'movies/edit.html', context)

def update(request, pk):
    update_review = Review.objects.get(id=pk)

    update_review.title = request.GET.get('title_')
    update_review.content = request.GET.get('content_')

    update_review.save()
    return redirect('movies:index')

movies/templates/movies/detail.html
{% extends 'base.html' %} {% block content %}
<style>
  .del-btn:hover {
    border-color: #A07EE7;
    background-color: white;
    color: #A07EE7;
  }
</style>

<div class="card mt-5 mb-5" style="border-color: #A07EE7;">
  <h2 class="d-flex justify-content-center mt-2">{{ title }}</h1>
  <hr style="color: white">
  <p class="d-flex justify-content-center mb-3" style="color: gray;">{{ content }}</p>
</div>
<div class="d-flex justify-content-center">
  <a href="{% url 'movies:edit' idx %}"
      ><button type="button" class="btn" style="margin-right: 5px; background-color: #BFA9E4; color: white;">리뷰 수정</button></a
  >
  <a href="{% url 'movies:delete' idx %}"
      ><button type="button" class="btn del-btn" style="margin-left: 5px; background-color: #A07EE7; border-color:#A07EE7; color: white;">리뷰 삭제</button></a
  >
</div>
{% endblock content %}

movies/templates/movies/edit.html
{% extends 'base.html' %} {% block content %}
<form action="{% url 'movies:update' edit.id %}">
    <div class="mt-4">
        <label for="title_" class="d-flex justify-content-center mb-1 fw-bold" style="font-size: 1.3rem; color: gray;"> <i class="bi bi-chat-square-heart"></i>　제목</label>
        <input
            class="form-control"
            id="title_"
            name="title_"
            type="text"
            aria-label="default input example"
            value="{{ edit.title }}"
            style="border-color: #A07EE7; color: gray;"
            autocomplete="off"
            required
        />
    </div>
    <div class="mt-4 mb-3">
        <label for="content_" class="form-label d-flex justify-content-center mb-1 fw-bold" style="font-size: 1.3rem; color: gray;"> <i class="bi bi-card-text"></i>　내용</label>
        <textarea
            class="form-control"
            id="content_"
            name="content_"
            rows="3"
            autocomplete="off"
            style="border-color: #A07EE7; color: gray;"
            required
        >
{{ edit.content }}
</textarea
        >
    </div>
    <input class="btn w-100" style="background-color: #A07EE7; color: white;" type="submit" value="리뷰 수정">
</form>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %} {% block content %}
<style>
    .idx-btn:hover {
        background-color: #FEF6FF;
    }
</style>

<a class="d-flex justify-content-end" style="text-decoration: none;" href="{% url 'movies:new' %}"><button type="button" class="idx-btn btn btn-outline mt-4 mb-4" style="border-color: #A07EE7; color: #A07EE7;"> <i class="bi bi-vector-pen"></i> 리뷰 작성</button></a>
<table class="table table-striped mt-2">
    <thead>
        <tr style="color: grey;">
            <th scope="col">리뷰 번호</th>
            <th scope="col">리뷰 제목</th>
            <th scope="col">작성 시간</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
        <tr>
            <td>{{ movie.id }}</td>
            <td>
                <a href="{% url 'movies:detail' movie.id %}" style="text-decoration: none; font-weight: bold; color: black;"
                    >{{ movie.title }}</a
                >
            </td>
            <td>{{ movie.created_at| date:'Y년 m월 d일'}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

movies/templates/movies/new.html
{% extends 'base.html' %} {% block content %}

<form action="{% url 'movies:create' %}">    
    <div class="mt-4">
        <label for="title_" class="d-flex justify-content-center mb-1 fw-bold" style="font-size: 1.3rem; color: gray;"> <i class="bi bi-chat-square-heart"></i>　제목</label>
        <input
            class="form-control"
            id="title_"
            name="title_"
            type="text"
            aria-label="default input example"
            style="border-color: #A07EE7; color: gray;"
            autocomplete="off"
            required
        />
    </div>
    <div class="mt-4 mb-3">
        <label for="content_" class="form-label d-flex justify-content-center mb-1 fw-bold" style="font-size: 1.3rem; color: gray;"> <i class="bi bi-card-text"></i>　내용</label>
        <textarea
            class="form-control"
            id="content_"
            name="content_"
            rows="3"
            autocomplete="off"
            style="border-color: #A07EE7; color: gray;"
            required
        ></textarea>
    </div>
    <input class="btn w-100" type="submit" style="background-color: #A07EE7; color: white;" type="submit" value="리뷰 쓰기">
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <title>Document</title>
    </head>
    <body>
        <div class="container">
        {% block content %} {% endblock content %}
        </div>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"
        ></script>
    </body>
</html>